// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"wire_sample/controller"
	"wire_sample/env"
	"wire_sample/repository"
	"wire_sample/repository/db"
	"wire_sample/service"
)

// Injectors from wire.go:

func NewController(e env.Conf) controller.Controller {
	sqlDB := db.OpenDB(e)
	repositoryRepository := repository.NewRepository(sqlDB)
	serviceService := service.NewService(repositoryRepository)
	controllerController := controller.NewController(serviceService)
	return controllerController
}
